---
- name: 'Updating apt repo/cache'
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: 'Upgrade all packages'
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: 'Installing Packages'
  package:
    name:
      - qemu-guest-agent
      - jq
      - netexec
      - burpsuite
      - neovim
    state: latest
  become: true
  become_method: sudo

- name: 'Cleanup unused packages'
  apt:
    autoremove: yes
    autoclean: yes
  become: true
  become_method: sudo

- name: 'Clean apt cache'
  apt:
    clean: yes
  become: true
  become_method: sudo
