---
- name: Download Docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  become: true

- name: Execute Docker install script
  command: sh /tmp/get-docker.sh
  register: docker_install
  changed_when: docker_install.rc == 0
  become: true

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default(ansible_facts['user_id']) }}"
    groups: docker
    append: yes
  become: true

- name: Clean up install script
  file:
    path: /tmp/get-docker.sh
    state: absent
